# Generated by Django 3.2.12 on 2023-01-29 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideSharer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(default='', max_length=100)),
                ('earliest_arrival_date', models.DateTimeField(help_text='Format: YYYY-MM-DD hh:mm:ss')),
                ('latest_arrival_date', models.DateTimeField(help_text='Format: YYYY-MM-DD hh:mm:ss')),
                ('tol_passengers', models.PositiveIntegerField(default=1)),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Share Details',
            },
        ),
        migrations.CreateModel(
            name='RideOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(default='', max_length=100)),
                ('arrival_date', models.DateTimeField(help_text='Format: YYYY-MM-DD hh:mm:ss')),
                ('tol_passengers', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='open', max_length=20)),
                ('shared', models.BooleanField(default=True)),
                ('vehicle_type', models.CharField(blank=True, default='', max_length=20)),
                ('special_reqs', models.TextField(blank=True, default='')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ride Details',
            },
        ),
    ]
