# Generated by Django 3.2.12 on 2023-01-30 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rideowner',
            options={'verbose_name': 'Ride Detail'},
        ),
        migrations.AlterModelOptions(
            name='ridesharer',
            options={'verbose_name': 'Share Detail'},
        ),
        migrations.AlterField(
            model_name='rideowner',
            name='arrival_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rideowner',
            name='shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ridesharer',
            name='earliest_arrival_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ridesharer',
            name='latest_arrival_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
