# Generated by Django 3.2.12 on 2023-01-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_auto_20230130_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideowner',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ridesharer',
            name='earliest_arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ridesharer',
            name='latest_arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rideowner',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ridesharer',
            name='earliest_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ridesharer',
            name='latest_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
