# Generated by Django 3.2.12 on 2023-01-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_auto_20230130_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideowner',
            name='driver_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
