# Generated by Django 3.2.12 on 2023-01-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_rideowner_driver_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ridesharer',
            old_name='destination',
            new_name='sha_destination',
        ),
        migrations.RenameField(
            model_name='ridesharer',
            old_name='tol_passengers',
            new_name='sha_tol_passengers',
        ),
    ]
