# Generated by Django 3.2.12 on 2023-02-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_auto_20230130_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridesharer',
            name='owner_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
