# Generated by Django 3.2.12 on 2023-02-02 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_driverprofile_seats'),
        ('rides', '0007_auto_20230201_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rideowner',
            name='driver_name',
        ),
        migrations.AddField(
            model_name='rideowner',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.driverprofile'),
        ),
    ]
