# Generated by Django 3.2.12 on 2023-02-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_auto_20230202_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideowner',
            name='tol_passenger_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
