# Generated by Django 3.2.12 on 2023-02-03 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_driverprofile_seats'),
        ('rides', '0010_alter_ridesharer_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideowner',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.driverprofile'),
        ),
    ]
