# Generated by Django 3.2.12 on 2023-01-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverprofile',
            options={'verbose_name': 'Driver Profile'},
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='phone_num',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
    ]
