# Generated by Django 3.2.12 on 2023-01-28 22:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20230128_2209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APPUser',
            new_name='UserProfile',
        ),
    ]
