# Generated by Django 3.2.12 on 2023-02-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_appuser_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
