# Generated by Django 3.2.12 on 2023-02-01 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_driverprofile_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='seats',
        ),
    ]
